from __future__ import annotations

from datetime import UTC, date, datetime
from uuid import UUID, uuid5


DATASET_VERSION = "phase-2-real-reports-v1"
PARSER_VERSION = "curated_seed_v1"
NOW = datetime.now(UTC)
NAMESPACE = UUID("41f07f43-652f-4126-bb96-e7d3ba23aa11")


def stable_id(*parts: str) -> UUID:
    return uuid5(NAMESPACE, "::".join(parts))


REAL_DATASET = [
    {
        "company": {
            "id": stable_id("company", "yh_dimri"),
            "name_he": "י.ח. דמרי",
            "name_en": "Y.H. Dimri Construction & Development Ltd",
            "ticker": "DIMRI",
        },
        "report": {
            "id": stable_id("report", "yh_dimri", "2025-q3"),
            "report_type": "q3",
            "period_type": "quarterly",
            "period_end_date": date(2025, 9, 30),
            "publish_date": date(2025, 11, 20),
            "filing_reference": "דוח רבעוני לרבעון השלישי לשנת 2025",
            "source_file_path": "https://ir.dimri.co.il/wp-content/uploads/2025/11/%D7%93%D7%95%D7%97-%D7%A8%D7%91%D7%A2%D7%95%D7%9F-3-%D7%9C%D7%A9%D7%A0%D7%AA-2025-.pdf",
        },
        "projects": [
            {
                "slug": "dimri-afeka-kiryat-bialik",
                "canonical_name": "דמרי אפקה",
                "city": "קריית ביאליק",
                "project_business_type": "regular_dev",
                "government_program_type": "none",
                "project_urban_renewal_type": "none",
                "classification_confidence": "medium",
                "project_status": "marketing",
                "permit_status": None,
                "total_units": 463,
                "marketed_units": 463,
                "sold_units_cumulative": 426,
                "unsold_units": 37,
                "source_pages": [24, 25],
                "source_section": "Residential marketing and execution table",
                "notes": [
                    "Project business type defaults to regular_dev because the source table does not explicitly mark a government program or urban-renewal track.",
                    "permit_status left null because the latest public report does not state a permit status for this project.",
                    "avg_price_per_sqm_cumulative left null because the source table does not disclose it.",
                ],
                "missing_fields": ["permit_status", "avg_price_per_sqm_cumulative", "gross_margin_expected_pct"],
            },
            {
                "slug": "yama-netanya-building-2",
                "canonical_name": "YAMA בניין 2",
                "city": "נתניה",
                "project_business_type": "regular_dev",
                "government_program_type": "none",
                "project_urban_renewal_type": "none",
                "classification_confidence": "medium",
                "project_status": "marketing",
                "permit_status": None,
                "total_units": 198,
                "marketed_units": 198,
                "sold_units_cumulative": 77,
                "unsold_units": 121,
                "source_pages": [24, 25],
                "source_section": "Residential marketing and execution table",
                "notes": [
                    "Project business type defaults to regular_dev because no special classification is explicit in the table.",
                    "permit_status left null because it is not disclosed in the latest public report.",
                ],
                "missing_fields": ["permit_status", "avg_price_per_sqm_cumulative", "gross_margin_expected_pct"],
            },
            {
                "slug": "harmony-ashdod-phase-b",
                "canonical_name": "HARMONY שלב ב'",
                "city": "אשדוד",
                "project_business_type": "regular_dev",
                "government_program_type": "none",
                "project_urban_renewal_type": "none",
                "classification_confidence": "medium",
                "project_status": "marketing",
                "permit_status": None,
                "total_units": 128,
                "marketed_units": 128,
                "sold_units_cumulative": 19,
                "unsold_units": 109,
                "source_pages": [24, 25],
                "source_section": "Residential marketing and execution table",
                "notes": ["permit_status left null because it is not stated in the latest public report."],
                "missing_fields": ["permit_status", "avg_price_per_sqm_cumulative", "gross_margin_expected_pct"],
            },
            {
                "slug": "afikei-hanahal-ofakim-blocks-2-4",
                "canonical_name": "אפיקי הנחל בלוקים 2+4",
                "city": "אופקים",
                "project_business_type": "regular_dev",
                "government_program_type": "none",
                "project_urban_renewal_type": "none",
                "classification_confidence": "medium",
                "project_status": "marketing",
                "permit_status": None,
                "total_units": 186,
                "marketed_units": 186,
                "sold_units_cumulative": 63,
                "unsold_units": 123,
                "source_pages": [24, 25],
                "source_section": "Residential marketing and execution table",
                "notes": ["permit_status left null because it is not disclosed in the report."],
                "missing_fields": ["permit_status", "avg_price_per_sqm_cumulative", "gross_margin_expected_pct"],
            },
        ],
    },
    {
        "company": {
            "id": stable_id("company", "aura"),
            "name_he": "אאורה",
            "name_en": "Aura Investments Ltd",
            "ticker": "AURA",
        },
        "report": {
            "id": stable_id("report", "aura", "2025-q3"),
            "report_type": "q3",
            "period_type": "quarterly",
            "period_end_date": date(2025, 9, 30),
            "publish_date": date(2025, 12, 23),
            "filing_reference": "דוחות אאורה ליום 30.9.2025",
            "source_file_path": "https://auraisrael.co.il/wp-content/uploads/2025/12/%D7%93%D7%95%D7%97%D7%95%D7%AA-%D7%90%D7%90%D7%95%D7%A8%D7%94-30.9.25.pdf",
        },
        "projects": [
            {
                "slug": "aura-ramat-hen-ramat-gan",
                "canonical_name": "אאורה רמת חן",
                "city": "רמת גן",
                "project_business_type": "urban_renewal",
                "government_program_type": "none",
                "project_urban_renewal_type": "other",
                "classification_confidence": "medium",
                "project_status": "construction",
                "permit_status": "granted",
                "total_units": 522,
                "marketed_units": 369,
                "sold_units_cumulative": 212,
                "unsold_units": 157,
                "source_pages": [16],
                "source_section": "Major projects with commenced construction and/or marketing",
                "notes": [
                    "Aura is an urban-renewal-focused developer and the project is reported within its residential project table, but the subtype is not explicit in the source table, so project_urban_renewal_type is set to other.",
                    "permit_status is inferred as granted because the report discloses an active construction completion rate.",
                    "avg_price_per_sqm_cumulative left null because the source report does not disclose it for this project.",
                ],
                "missing_fields": ["avg_price_per_sqm_cumulative"],
            },
            {
                "slug": "project-haoren-kiryat-ono",
                "canonical_name": "פרויקט האורן",
                "city": "קריית אונו",
                "project_business_type": "urban_renewal",
                "government_program_type": "none",
                "project_urban_renewal_type": "pinui_binui",
                "classification_confidence": "high",
                "project_status": "construction",
                "permit_status": "granted",
                "total_units": 305,
                "marketed_units": 209,
                "sold_units_cumulative": 137,
                "unsold_units": 72,
                "source_pages": [16, 18],
                "source_section": "Major projects table and notes identifying Pinui Binui",
                "notes": [
                    "Pinui Binui classification is taken from the report footnote naming the project as a Pinui Binui project.",
                    "permit_status is inferred as granted because the report discloses active construction progress.",
                ],
                "missing_fields": ["avg_price_per_sqm_cumulative"],
            },
            {
                "slug": "ben-shemen-lod-lot-104",
                "canonical_name": "בן שמן מגרש 104",
                "city": "לוד",
                "project_business_type": "regular_dev",
                "government_program_type": "none",
                "project_urban_renewal_type": "none",
                "classification_confidence": "medium",
                "project_status": "construction",
                "permit_status": "granted",
                "total_units": 102,
                "marketed_units": 102,
                "sold_units_cumulative": 88,
                "unsold_units": 14,
                "source_pages": [16],
                "source_section": "Major projects with commenced construction and/or marketing",
                "notes": [
                    "Business type defaults to regular_dev because the report table does not explicitly identify a government or urban-renewal track for this project.",
                    "permit_status is inferred as granted from the disclosed completion rate.",
                ],
                "missing_fields": ["avg_price_per_sqm_cumulative"],
            },
            {
                "slug": "link-yehud-shuk-ashkenazi",
                "canonical_name": "LINK (שוק אשכנזי)",
                "city": "יהוד",
                "project_business_type": "regular_dev",
                "government_program_type": "none",
                "project_urban_renewal_type": "none",
                "classification_confidence": "low",
                "project_status": "construction",
                "permit_status": "granted",
                "total_units": 444,
                "marketed_units": 328,
                "sold_units_cumulative": 172,
                "unsold_units": 156,
                "source_pages": [16],
                "source_section": "Major projects with commenced construction and/or marketing",
                "notes": [
                    "Business type is left as regular_dev with low confidence because the source table does not explicitly label the project business track.",
                    "permit_status is inferred as granted from the reported completion rate.",
                ],
                "missing_fields": ["avg_price_per_sqm_cumulative"],
            },
        ],
    },
    {
        "company": {
            "id": stable_id("company", "azorim"),
            "name_he": "אזורים",
            "name_en": "Azorim-Investment, Development and Construction Co. Ltd",
            "ticker": "AZRM",
        },
        "report": {
            "id": stable_id("report", "azorim", "2025-q3"),
            "report_type": "q3",
            "period_type": "quarterly",
            "period_end_date": date(2025, 9, 30),
            "publish_date": None,
            "filing_reference": "דוח רבעון שלישי 2025 מונגש",
            "source_file_path": "https://ir.azorim.co.il/wp-content/uploads/2025/11/%D7%90%D7%96%D7%95%D7%A8%D7%99%D7%9D-%D7%94%D7%A9%D7%A7%D7%A2%D7%95%D7%AA-%D7%93%D7%95%D7%97-%D7%A8%D7%91%D7%A2%D7%95%D7%9F-%D7%A9%D7%9C%D7%99%D7%A9%D7%99-2025-%D7%9E%D7%95%D7%A0%D7%92%D7%A9.pdf",
        },
        "projects": [
            {
                "slug": "exchange-ramat-gan",
                "canonical_name": "Exchange",
                "city": "רמת גן",
                "project_business_type": "regular_dev",
                "government_program_type": "none",
                "project_urban_renewal_type": "none",
                "classification_confidence": "medium",
                "project_status": "marketing",
                "permit_status": None,
                "total_units": 355,
                "marketed_units": 355,
                "sold_units_cumulative": 244,
                "unsold_units": 111,
                "source_pages": [14],
                "source_section": "Projects in marketing / execution table",
                "notes": [
                    "publish_date left null because the direct PDF source did not expose an exact publication date in the extracted text used for seeding.",
                    "permit_status left null because it is not explicitly disclosed in the table.",
                ],
                "missing_fields": ["published_at", "permit_status", "avg_price_per_sqm_cumulative"],
            },
            {
                "slug": "shaar-hair-jerusalem",
                "canonical_name": "שער העיר",
                "city": "ירושלים",
                "project_business_type": "regular_dev",
                "government_program_type": "none",
                "project_urban_renewal_type": "none",
                "classification_confidence": "medium",
                "project_status": "marketing",
                "permit_status": None,
                "total_units": 229,
                "marketed_units": 229,
                "sold_units_cumulative": 151,
                "unsold_units": 78,
                "source_pages": [14],
                "source_section": "Projects in marketing / execution table",
                "notes": ["permit_status left null because it is not explicitly disclosed in the table."],
                "missing_fields": ["permit_status", "avg_price_per_sqm_cumulative"],
            },
            {
                "slug": "park-hayam-bat-yam",
                "canonical_name": "פארק הים",
                "city": "בת ים",
                "project_business_type": "regular_dev",
                "government_program_type": "none",
                "project_urban_renewal_type": "none",
                "classification_confidence": "medium",
                "project_status": "marketing",
                "permit_status": None,
                "total_units": 393,
                "marketed_units": 393,
                "sold_units_cumulative": 318,
                "unsold_units": 75,
                "source_pages": [14],
                "source_section": "Projects in marketing / execution table",
                "notes": ["permit_status left null because it is not explicitly disclosed in the table."],
                "missing_fields": ["permit_status", "avg_price_per_sqm_cumulative"],
            },
            {
                "slug": "we-live-tel-aviv",
                "canonical_name": "We Live",
                "city": "תל אביב",
                "project_business_type": "regular_dev",
                "government_program_type": "none",
                "project_urban_renewal_type": "none",
                "classification_confidence": "low",
                "project_status": "marketing",
                "permit_status": None,
                "total_units": 219,
                "marketed_units": 219,
                "sold_units_cumulative": 165,
                "unsold_units": 54,
                "source_pages": [14],
                "source_section": "Projects in marketing / execution table",
                "notes": [
                    "Business type defaults to regular_dev with low confidence because the source table does not explicitly classify the project beyond residential activity.",
                    "permit_status left null because it is not disclosed in the latest public report.",
                ],
                "missing_fields": ["permit_status", "avg_price_per_sqm_cumulative"],
            },
        ],
    },
    {
        "company": {
            "id": stable_id("company", "amram_avraham"),
            "name_he": "עמרם אברהם",
            "name_en": "Amram Avraham Construction Company Ltd",
            "ticker": "AMRM",
        },
        "report": {
            "id": stable_id("report", "amram_avraham", "2025-q3"),
            "report_type": "q3",
            "period_type": "quarterly",
            "period_end_date": date(2025, 9, 30),
            "publish_date": date(2025, 11, 27),
            "filing_reference": "דוח רבעוני Q3 שנת 2025",
            "source_file_path": "https://amramltd.co.il/wp-content/uploads/2026/03/Q3-2025.pdf",
        },
        "projects": [
            {
                "slug": "aqua-havatzelet-hasharon-complex-kaf",
                "canonical_name": "אקווה חבצלת השרון מתחם כ'",
                "city": "נתניה",
                "project_business_type": "govt_program",
                "government_program_type": "mechir_metara",
                "project_urban_renewal_type": "none",
                "classification_confidence": "high",
                "project_status": "planning",
                "permit_status": None,
                "total_units": 128,
                "marketed_units": 128,
                "sold_units_cumulative": None,
                "unsold_units": None,
                "source_pages": [17],
                "source_section": "Upcoming projects table",
                "notes": [
                    "Government program classification is explicit because the source table labels the project as מחיר מטרה + שוק חופשי.",
                    "sold_units_cumulative and unsold_units are left null because the project is disclosed as an upcoming project and the report does not provide sales numbers.",
                ],
                "missing_fields": ["sold_units_cumulative", "unsold_units", "permit_status", "avg_price_per_sqm_cumulative"],
            },
            {
                "slug": "aqua-havatzelet-hasharon-complex-aleph",
                "canonical_name": "אקווה חבצלת השרון מתחם א'",
                "city": "נתניה",
                "project_business_type": "govt_program",
                "government_program_type": "mechir_metara",
                "project_urban_renewal_type": "none",
                "classification_confidence": "high",
                "project_status": "planning",
                "permit_status": None,
                "total_units": 150,
                "marketed_units": 150,
                "sold_units_cumulative": None,
                "unsold_units": None,
                "source_pages": [17],
                "source_section": "Upcoming projects table",
                "notes": ["Government program classification is explicit because the source table labels the project as מחיר מטרה + שוק חופשי."],
                "missing_fields": ["sold_units_cumulative", "unsold_units", "permit_status", "avg_price_per_sqm_cumulative"],
            },
            {
                "slug": "kfar-saba-kiryat-hatzairim",
                "canonical_name": "כפר סבא קריית הצעירים",
                "city": "כפר סבא",
                "project_business_type": "govt_program",
                "government_program_type": "mechir_metara",
                "project_urban_renewal_type": "none",
                "classification_confidence": "high",
                "project_status": "planning",
                "permit_status": None,
                "total_units": 73,
                "marketed_units": 73,
                "sold_units_cumulative": None,
                "unsold_units": None,
                "source_pages": [17],
                "source_section": "Upcoming projects table",
                "notes": ["Source table labels the project as שוק חופשי + מחיר מטרה, so the business type is kept as govt_program under the normalization priority rules."],
                "missing_fields": ["sold_units_cumulative", "unsold_units", "permit_status", "avg_price_per_sqm_cumulative"],
            },
            {
                "slug": "bnei-ayish-complex-73146",
                "canonical_name": "בני עייש מתחם 73146",
                "city": "בני עייש",
                "project_business_type": "govt_program",
                "government_program_type": "mechir_metara",
                "project_urban_renewal_type": "none",
                "classification_confidence": "high",
                "project_status": "planning",
                "permit_status": None,
                "total_units": 132,
                "marketed_units": 132,
                "sold_units_cumulative": None,
                "unsold_units": None,
                "source_pages": [17],
                "source_section": "Upcoming projects table",
                "notes": ["Source table labels the project as שוק חופשי + מחיר מטרה, so the business type is kept as govt_program under the normalization priority rules."],
                "missing_fields": ["sold_units_cumulative", "unsold_units", "permit_status", "avg_price_per_sqm_cumulative"],
            },
        ],
    },
    {
        "company": {
            "id": stable_id("company", "africa_israel_residences"),
            "name_he": "אפריקה ישראל מגורים",
            "name_en": "Africa Israel Residences Ltd",
            "ticker": "AFRE",
        },
        "report": {
            "id": stable_id("report", "africa_israel_residences", "2025-q3"),
            "report_type": "q3",
            "period_type": "quarterly",
            "period_end_date": date(2025, 9, 30),
            "publish_date": date(2025, 11, 30),
            "filing_reference": "דוח ליום 30.9.2025",
            "source_file_path": "https://cdn.financialreports.eu/financialreports/media/filings/6625/2025/RNS/6625_rns_2025-11-30_c050d6ad-d0d6-455f-bcbd-c2129232568c.pdf",
        },
        "projects": [
            {
                "slug": "zeev-jabotinsky-135-137-tel-aviv",
                "canonical_name": "ז'בוטינסקי 135-137",
                "city": "תל אביב",
                "project_business_type": "regular_dev",
                "government_program_type": "none",
                "project_urban_renewal_type": "none",
                "classification_confidence": "low",
                "project_status": "marketing",
                "permit_status": None,
                "total_units": 68,
                "marketed_units": 34,
                "sold_units_cumulative": 9,
                "unsold_units": 25,
                "source_pages": [26],
                "source_section": "Projects in marketing before execution",
                "notes": ["Business type defaults to regular_dev with low confidence because the table does not explicitly label a program or urban-renewal track."],
                "missing_fields": ["permit_status", "avg_price_per_sqm_cumulative"],
            },
            {
                "slug": "kitzis-tel-aviv",
                "canonical_name": "קיציס",
                "city": "תל אביב",
                "project_business_type": "regular_dev",
                "government_program_type": "none",
                "project_urban_renewal_type": "none",
                "classification_confidence": "low",
                "project_status": "marketing",
                "permit_status": None,
                "total_units": 178,
                "marketed_units": 98,
                "sold_units_cumulative": 21,
                "unsold_units": 77,
                "source_pages": [26],
                "source_section": "Projects in marketing before execution",
                "notes": ["The latest source table does not specify whether this project is urban renewal or regular development, so the normalization fallback is regular_dev with low confidence."],
                "missing_fields": ["permit_status", "avg_price_per_sqm_cumulative"],
            },
            {
                "slug": "gabrielov-rehovot",
                "canonical_name": "גבריאלוב",
                "city": "רחובות",
                "project_business_type": "regular_dev",
                "government_program_type": "none",
                "project_urban_renewal_type": "none",
                "classification_confidence": "low",
                "project_status": "marketing",
                "permit_status": None,
                "total_units": 156,
                "marketed_units": 126,
                "sold_units_cumulative": 10,
                "unsold_units": 116,
                "source_pages": [26],
                "source_section": "Projects in marketing before execution",
                "notes": ["The latest source table does not specify whether this project is urban renewal or regular development, so the normalization fallback is regular_dev with low confidence."],
                "missing_fields": ["permit_status", "avg_price_per_sqm_cumulative"],
            },
            {
                "slug": "agmei-bereshit-stage-a-nesher",
                "canonical_name": "אגמי בראשית שלב א'",
                "city": "נשר",
                "project_business_type": "regular_dev",
                "government_program_type": "none",
                "project_urban_renewal_type": "none",
                "classification_confidence": "medium",
                "project_status": "marketing",
                "permit_status": None,
                "total_units": 232,
                "marketed_units": 232,
                "sold_units_cumulative": 126,
                "unsold_units": 106,
                "source_pages": [26],
                "source_section": "Projects in marketing before execution",
                "notes": ["permit_status left null because the source table does not explicitly disclose it."],
                "missing_fields": ["permit_status", "avg_price_per_sqm_cumulative"],
            },
        ],
    },
]
